# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/choreo_k_refactor',
                'doc_host': 'https://broadwell.github.io',
                'git_url': 'https://github.com/broadwell/choreo_k_refactor',
                'lib_path': 'choreo_k_refactor'},
  'syms': {'choreo_k_refactor.core': {'choreo_k_refactor.core.foo': ('core.html#foo', 'choreo_k_refactor/core.py')}}}